//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVProje2.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVDbEntities : DbContext
    {
        public CVDbEntities()
            : base("name=CVDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SosyalMedya> SosyalMedya { get; set; }
        public virtual DbSet<TblAnasayfa> TblAnasayfa { get; set; }
        public virtual DbSet<TblBlog> TblBlog { get; set; }
        public virtual DbSet<TblEğitimDeneyim> TblEğitimDeneyim { get; set; }
        public virtual DbSet<TblHakkimdaa> TblHakkimdaa { get; set; }
        public virtual DbSet<Tbliletisim> Tbliletisim { get; set; }
        public virtual DbSet<TblProjeler> TblProjeler { get; set; }
        public virtual DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblReferanslar> TblReferanslar { get; set; }
    }
}
