//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVProje2.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEğitimDeneyim
    {
        public int ID { get; set; }
        public string ETarih { get; set; }
        public string EBaslik { get; set; }
        public string EAciklama { get; set; }
        public string GNO { get; set; }
        public string DTarih { get; set; }
        public string DBaslik { get; set; }
        public string Pozisyon { get; set; }
        public string DAciklama { get; set; }
        public string ProjeSayısı { get; set; }
    }
}
