//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVProje2.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjeler
    {
        public int ID { get; set; }
        public string Resim { get; set; }
        public string Kategori { get; set; }
        public string Bağlantı { get; set; }
    }
}
